template_path: deployment-target-account.yaml

parameters:
  DeploymentAccount: !environment_variable ACCOUNT_ID
  DlqName: {{stack_group_config.dlq_name}}
  StackEventsTopic: {{stack_group_config.events_topic_name}}
  ProjectName: aws-bills-to-telegram
