template_path: template.yaml

region: us-east-1

parameters:
  IntervalHours: '24'
  DlqName: {{stack_group_config.dlq_name}}
  StackEventsTopic: {{stack_group_config.events_topic_name}}
  TelegramBotToken: !aws ssm::get_parameter::'Name':'bot-token','WithDecryption':True::Parameter.Value::us-east-1
  TelegramChatId: !aws ssm::get_parameter::'Name':'/bills-to-telegram/chat-id'::Parameter.Value::us-east-1
