template_path: template.yaml

region: us-east-1

parameters:
  DlqName: {{stack_group_config.dlq_name}}
  IntervalHours: '24'
  Role: !stack_output app/dev/base.yaml::FnRole
  TelegramBotToken: !aws ssm::get_parameter::'Name':'bot-token','WithDecryption':True::Parameter.Value::us-east-1
  TelegramChatId: !aws ssm::get_parameter::'Name':'/bills-to-telegram/chat-id'::Parameter.Value::us-east-1
